name: Sync to Gitee

on: [push]

permissions:
  contents: read

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H gitee.com >> ~/.ssh/known_hosts

      - name: Sync to Gitee
        run: |
          git remote add gitee git@gitee.com:ccandzy/daily-english.git
          git push gitee main --force --tags
